/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateCreditCard.Sdk {

using System;
using System.Runtime.InteropServices;

public class UltCreditCardSdkEngine : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal UltCreditCardSdkEngine(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(UltCreditCardSdkEngine obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~UltCreditCardSdkEngine() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ultimateCreditCardSdkPINVOKE.delete_UltCreditCardSdkEngine(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public static UltCreditCardSdkResult init(string jsonConfig) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_init__SWIG_0(jsonConfig), true);
    return ret;
  }

  public static UltCreditCardSdkResult init() {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_init__SWIG_1(), true);
    return ret;
  }

  public static UltCreditCardSdkResult deInit() {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_deInit(), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples, int imageExifOrientation) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_0((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples, imageExifOrientation), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples, uint imageStrideInSamples) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_1((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples, imageStrideInSamples), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr imageData, uint imageWidthInSamples, uint imageHeightInSamples) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_2((int)imageType, imageData, imageWidthInSamples, imageHeightInSamples), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes, int exifOrientation) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_3((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes, exifOrientation), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes, uint uvPixelStrideInBytes) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_4((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes, uvPixelStrideInBytes), true);
    return ret;
  }

  public static UltCreditCardSdkResult process(ULTCCARD_SDK_IMAGE_TYPE imageType, IntPtr yPtr, IntPtr uPtr, IntPtr vPtr, uint widthInSamples, uint heightInSamples, uint yStrideInBytes, uint uStrideInBytes, uint vStrideInBytes) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_process__SWIG_5((int)imageType, yPtr, uPtr, vPtr, widthInSamples, heightInSamples, yStrideInBytes, uStrideInBytes, vStrideInBytes), true);
    return ret;
  }

  public static int exifOrientation(IntPtr jpegMetaDataPtr, uint jpegMetaDataSize) {
    int ret = ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_exifOrientation(jpegMetaDataPtr, jpegMetaDataSize);
    return ret;
  }

  public static UltCreditCardSdkResult requestRuntimeLicenseKey(bool rawInsteadOfJSON) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_requestRuntimeLicenseKey__SWIG_0(rawInsteadOfJSON), true);
    return ret;
  }

  public static UltCreditCardSdkResult requestRuntimeLicenseKey() {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_requestRuntimeLicenseKey__SWIG_1(), true);
    return ret;
  }

  public static UltCreditCardSdkResult warmUp(ULTCCARD_SDK_IMAGE_TYPE imageType) {
    UltCreditCardSdkResult ret = new UltCreditCardSdkResult(ultimateCreditCardSdkPINVOKE.UltCreditCardSdkEngine_warmUp((int)imageType), true);
    return ret;
  }

}

}
