/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace org.doubango.ultimateCreditCard.Sdk {

using System;
using System.Runtime.InteropServices;

public class ultimateCreditCardSdk {
  public static readonly int ULTCCARD_SDK_VERSION_MAJOR = ultimateCreditCardSdkPINVOKE.ULTCCARD_SDK_VERSION_MAJOR_get();
  public static readonly int ULTCCARD_SDK_VERSION_MINOR = ultimateCreditCardSdkPINVOKE.ULTCCARD_SDK_VERSION_MINOR_get();
  public static readonly int ULTCCARD_SDK_VERSION_MICRO = ultimateCreditCardSdkPINVOKE.ULTCCARD_SDK_VERSION_MICRO_get();
}

}
