/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateCreditCard.Sdk;

public class UltCreditCardSdkResult {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UltCreditCardSdkResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UltCreditCardSdkResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ultimateCreditCardSdkJNI.delete_UltCreditCardSdkResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UltCreditCardSdkResult(int code, String phrase, String json, long numCards) {
    this(ultimateCreditCardSdkJNI.new_UltCreditCardSdkResult__SWIG_0(code, phrase, json, numCards), true);
  }

  public UltCreditCardSdkResult(int code, String phrase, String json) {
    this(ultimateCreditCardSdkJNI.new_UltCreditCardSdkResult__SWIG_1(code, phrase, json), true);
  }

  public int code() {
    return ultimateCreditCardSdkJNI.UltCreditCardSdkResult_code(swigCPtr, this);
  }

  public String phrase() {
    return ultimateCreditCardSdkJNI.UltCreditCardSdkResult_phrase(swigCPtr, this);
  }

  public String json() {
    return ultimateCreditCardSdkJNI.UltCreditCardSdkResult_json(swigCPtr, this);
  }

  public long numCards() {
    return ultimateCreditCardSdkJNI.UltCreditCardSdkResult_numCards(swigCPtr, this);
  }

  public boolean isOK() {
    return ultimateCreditCardSdkJNI.UltCreditCardSdkResult_isOK(swigCPtr, this);
  }

}
