/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.ultimateCreditCard.Sdk;

public interface ultimateCreditCardSdkConstants {
  public final static int ULTCCARD_SDK_VERSION_MAJOR = 2;
  public final static int ULTCCARD_SDK_VERSION_MINOR = 2;
  public final static int ULTCCARD_SDK_VERSION_MICRO = 0;
}
